// Generated by https://quicktype.io

export interface CardMessage {
  cards: Card[];
}

export interface Card {
  header: Header;
  sections: Section[];
}

export interface Header {
  title: string;
  subtitle?: string;
  imageUrl?: string;
}

export interface Section {
  widgets: Widget[];
  header?: string;
}

export interface Widget {
  keyValue?: KeyValue;
  image?: Image;
  buttons?: Button[];
  textParagraph?: TextParagraph;
}

export interface TextParagraph {
    text: string
}

export interface Button {
  textButton: TextButton;
}

export interface TextButton {
  text: string;
  onClick: OnClick;
}

export interface OnClick {
  openLink: OpenLink;
}

export interface OpenLink {
  url: string;
}

export interface Image {
  imageUrl: string;
}

export interface KeyValue {
  iconUrl?: string;
  icon?: string;
  topLabel: string;
  content: string;
  contentMultiline?: boolean;
  bottomLabel?: string;
  onClick?: OnClick;
  button?: Button;
}
