# This will automatically build the Typescript files 

name: Build Typescript

on:
  push:
    branches: [ master, beta ]
  pull_request:
    branches: [ master, beta ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.5
      - run: npm ci
      - run: npm run build
